name: afqsm_mobile
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  image_picker: ^0.8.6
  http: ^0.13.5
  path_provider: ^2.0.11
  tflite_flutter: ^0.10.0  # for offline inference
